openapi: 3.0.0

info:
  description: Groovyschool is an online learning platform for technologies in the Groovy ecosystem.
  version: 1.0.0
  title: GROOVYSCHOOL API

paths:
  /register:
    post:
      summary: Register New User
      description: Create the accout of a new student in our system
      operationId: registerUser
      requestBody:
        content:
            application/json:
              schema:
                $ref: 'schemas/User.yaml'
      responses:
        '200':
          description: ok
        '405':
          description: Invalid input
    
    /login-request:
    post:
      description: A request for login
      operationId: loginRequest
      requestBody:
        content:
            application/json:
              schema:
                $ref: 'schemas/User.yaml'
      responses:
        '200':
          description: ok
        '405':
          description: User not found

    /login:
    post:
      description: login in a user of our system
      operationId: login
      requestBody:
        content:
            application/json:
              schema:
                $ref: 'schemas/User.yaml'
      responses:
        '200':
          description: Successful login
        '400':
          description: Invalid username/password entered
         


    /logut:
    post:
      description: Loging out a user from the system
      operationId: logoutRequest
      requestBody:
        content:
            application/json:
              schema:
                $ref: 'schemas/User.yaml'
      responses:
        '200':
          description: Successful logout
        '405':
          description: Operation failed

    /reset-password:
    post:
      description: A request for resetting a password
      operationId: reset-passwordRequest
      requestBody:
        content:
            application/json:
              schema:
                $ref: 'schemas/User.yaml'
      responses:
        '200':
          description: Successful Reset
        '405':
          description: Operation Denied