openapi: 3.0.0

info:
  description: Groovyschool is an online learning platform for technologies in the Groovy ecosystem.
  version: 1.0.0
  title: GROOVYSCHOOL API

paths:
  /register:
    post:
      summary: Register New User
      description: Create the accout of a new student in our system
      operationId: registerUser
      requestBody:
        content:
            application/json:
              schema:
                $ref: 'schemas/User.yaml'
    responses:
        '200':
          description: ok
        '405':
          description: Invalid input