openapi: 3.0.0

info:
  description: Groovyschool is an online learning platform for technologies in the Groovy ecosystem.
  version: 1.0.0
  title: GROOVYSCHOOL API

paths:
  /register:
    post:
      summary: Register New User
      description: Create the accout of a new student in our system
      operationId: registerUser
      requestBody:
        content:
            application/json:
              schema:
                $ref: 'schemas/User.yaml'
      responses:
        '200':
          description: ok
        '405':
          description: Invalid input
    
    /login-request:
    header:
    post:
      summary: Requests for login
      security:
        - OAuth2: [admin]
      operationId: loginRequest
      requestBody:
        content:
            application/json:
              schema:
                $ref: 'schemas/User.yaml'
      responses:
        '200':
          description: ok
        '405':
          description: User not found

    /login:
    
    {
      "alg": "HS256",
      "typ": "JWT"
    }

    payload:
      {
        "sub": "password",
        "name": "usernamehere",
        'email': 'email@address.com'
        "iat": 1516239022
      }

    signature:
      HMACSHA256(
      base64UrlEncode(header) + "." +
      base64UrlEncode(payload),
      secret_key
      ) 

    post:
      description: login in a user of our system
      operationId: login
      requestBody:
        content:
            application/json:
              schema:
                $ref: 'schemas/User.yaml'
      responses:
        '200':
          description: Successful login
        '400':
          description: Invalid username/password entered 
    get:
      description: login in a user of our system
      operationId: login
      requestBody:
        content:
            application/json:
              schema:
                $ref: 'schemas/User.yaml'
      responses:
        '200':
          description: Successful login
        '400':
          description: Password not found

    /logut:
    post:
      description: Log out a user from the system
      security:
        - OAuth2: [admin]
      operationId: logoutRequest
      requestBody:
        content:
            application/json:
              schema:
                $ref: 'schemas/User.yaml'
      responses:
        '200':
          description: Successful logout
        '405':
          description: Operation failed

    /reset-password:
    post:
      description: A request for resetting a password
      security:
        - OAuth2: [admin]
      operationId: reset-passwordRequest
      requestBody:
        content:
            application/json:
              schema:
                $ref: 'schemas/User.yaml'
      responses:
        '200':
          description: Successful Reset
        '405':
          description: Operation Denied

    get:
      description: A request for resetting a password
      security:
        - OAuth2: [admin]
      operationId: reset-passwordRequest
      requestBody:
        content:
            application/json:
              schema:
                $ref: 'schemas/User.yaml'
      responses:
        '200':
          description: Successful Reset
        '405':
          description: Reset failed

